version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Pre-game testing
          command: gem install rake -v 10.0 && gem install rspec -v 3.0
      - run:
          name: Run Tests
          command: bundle exec rake spec